


BATCH_NORM: True
PRETRAINED_MODELS_PATH: ''
PRETRAINED_MODEL_NAME: 'VGG16'
PRETRAINED_FEATURE_EXTRACTOR: True

MAX_NUM_EPOCS: 30
BATCH_SIZE: 5
ID_MAP_FNAME: 'all_instance_id_map.txt'

FULL_MODEL_LOAD_PATH: '/net/bvisionserver3/playpen/ammirato/Data/Detections/saved_models/'
LOAD_FULL_MODEL: False

PRELOAD_TARGET_IMAGES: False
AUGMENT_TARGET_IMAGES: True
TARGET_IMAGE_PATH: '/net/bvisionserver3/playpen10/ammirato/Data/instance_detection_targets/AVD_BB_exact_few_and_other_BB_gen_and_AVD_ns_BB_80/'

TRAIN_LIST: 
            - 'Home_101_1'
            - 'Home_102_1'
            - 'Home_103_1'
            - 'Home_104_1'
            - 'Home_105_1'
            - 'Home_106_1'
            - 'Home_107_1'
            - 'Home_108_1'
            - 'Home_109_1'
            - 'Home_109_1'
            -  'Gen_009_4'
            -  'Gen_009_4'
VAL_LIST: 
            - 'Home_001_1',
TRAIN_OBJ_IDS_RANGE:
            - 1
            - 30
TRAIN_OBJ_IDS_TO_EXCLUDE:
            - 28
            - 29
            - 30
            - 18
            - 8       
VAL_OBJ_IDS:
            - 1
            - 2
            - 3
            - 4
            - 5

MAX_OBJ_DIFFICULTY: 4







IS_MULTISCALE: False
NET_NAME: VGGnet
ANCHOR_SCALES: [2,4,8]
NCLASSES: 2 
TRAIN:
  OHEM: False
  RPN_BATCHSIZE: 300
  BATCH_SIZE: 300
  LOG_IMAGE_ITERS: 100
  DISPLAY: 10
  SNAPSHOT_ITERS: 5000
  HAS_RPN: True
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  GAMMA: 0.1
  STEPSIZE: 60000
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: False
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  PRECLUDE_HARD_SAMPLES: True
  BBOX_INSIDE_WEIGHTS: [1, 1, 1, 1]
  RPN_BBOX_INSIDE_WEIGHTS: [1, 1, 1, 1]
  RPN_POSITIVE_WEIGHT: -1.0
  FG_FRACTION: 0.3
  WEIGHT_DECAY: 0.0005
TEST:
  HAS_RPN: True
